version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - dogs_network
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=mongodb://db:27017/
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dogs_network

networks:
  dogs_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
